### PR TITLE
[MISC] Reenable caching

### PR DESCRIPTION
**Pull request by dragomirp**
Re-enable cached packing

### CODE REVIEW

**Review by welpaolo — APPROVED** [review]
Since Juju 3.6 LTS is out, is it better to jump to 3.6/stable ?

**Comment by dragomirp** [comment]
> Since Juju 3.6 LTS is out, is it better to jump to 3.6/stable ?

Let's give it a go as a separate matrix entry. I don't think any of the downstream charms switched, so better to keep 3.5 and 3.1 for the time being.

**Review by taurus-forever — APPROVED** [review]

**Comment by dragomirp** [comment]
@welpaolo @taurus-forever: Seems like Juju 3.5 and 3.6 are causing instability in the microk8s test. Merging just the cached building, to reenable release. Will investigate the Juju update at a later date.

**Comment by dragomirp** [comment]
Added https://github.com/canonical/charm-rolling-ops/issues/36 to track the juju 3.5/3.6 issues.

**Review by welpaolo — APPROVED** [review]

**Pull request merged**
